//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Account_Activity
    {
        public int ID { get; set; }
        public int User_Id { get; set; }
        public string Browser { get; set; }
        public string IP_Address { get; set; }
        public System.DateTime Access_Date { get; set; }
    
        public virtual FF_Registration FF_Registration { get; set; }
    }
}
