//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Cart_List
    {
        public int ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public int Product_ID { get; set; }
        public string Product_Price { get; set; }
        public string Temp_UserName { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual FF_Products FF_Products { get; set; }
    }
}
