//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Category
    {
        public FF_Category()
        {
            this.FF_HomePage_Display_Product = new HashSet<FF_HomePage_Display_Product>();
            this.FF_Products = new HashSet<FF_Products>();
            this.FF_Sub_Category = new HashSet<FF_Sub_Category>();
        }
    
        public int ID { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual FF_Category FF_Category1 { get; set; }
        public virtual FF_Category FF_Category2 { get; set; }
        public virtual ICollection<FF_HomePage_Display_Product> FF_HomePage_Display_Product { get; set; }
        public virtual ICollection<FF_Products> FF_Products { get; set; }
        public virtual ICollection<FF_Sub_Category> FF_Sub_Category { get; set; }
    }
}
