//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Pet_Details
    {
        public int ID { get; set; }
        public int User_ID { get; set; }
        public string Pet_Name { get; set; }
        public string Pet_Breed { get; set; }
        public string Pet_Gender { get; set; }
        public string Pet_Age { get; set; }
        public string Pet_Weight { get; set; }
    
        public virtual FF_Donate_Blood FF_Donate_Blood { get; set; }
    }
}
