//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Purchase_Order_List
    {
        public int ID { get; set; }
        public int User_Id { get; set; }
        public int Product_Id { get; set; }
        public string Order_Id { get; set; }
        public string Product_Price { get; set; }
        public int Quantity { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public bool Ispayment_Done { get; set; }
        public string Order_Status { get; set; }
        public Nullable<System.DateTime> Dispatch_Date { get; set; }
        public Nullable<System.DateTime> Delivered_Date { get; set; }
        public Nullable<System.DateTime> Return_Date { get; set; }
    
        public virtual FF_Products FF_Products { get; set; }
    }
}
