//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Products
    {
        public FF_Products()
        {
            this.FF_Cart_List = new HashSet<FF_Cart_List>();
            this.FF_Invoice_Table = new HashSet<FF_Invoice_Table>();
            this.FF_Purchase_Order_List = new HashSet<FF_Purchase_Order_List>();
            this.FF_Variants_Value = new HashSet<FF_Variants_Value>();
            this.FF_Wish_List = new HashSet<FF_Wish_List>();
        }
    
        public int ID { get; set; }
        public int Category_ID { get; set; }
        public int Sub_Category_ID { get; set; }
        public int User_ID { get; set; }
        public string Brand { get; set; }
        public string Product_Name { get; set; }
        public string Product_Code { get; set; }
        public string Price { get; set; }
        public string Quantity { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Discount { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public Nullable<bool> IsProduct_Hide { get; set; }
    
        public virtual ICollection<FF_Cart_List> FF_Cart_List { get; set; }
        public virtual FF_Category FF_Category { get; set; }
        public virtual ICollection<FF_Invoice_Table> FF_Invoice_Table { get; set; }
        public virtual FF_Products FF_Products1 { get; set; }
        public virtual FF_Products FF_Products2 { get; set; }
        public virtual ICollection<FF_Purchase_Order_List> FF_Purchase_Order_List { get; set; }
        public virtual ICollection<FF_Variants_Value> FF_Variants_Value { get; set; }
        public virtual ICollection<FF_Wish_List> FF_Wish_List { get; set; }
    }
}
