//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FF_Variants_Value
    {
        public FF_Variants_Value()
        {
            this.FF_Product_SubTable = new HashSet<FF_Product_SubTable>();
        }
    
        public int ID { get; set; }
        public int Product_Id { get; set; }
        public int Variants_Id { get; set; }
        public string Variants_Value { get; set; }
    
        public virtual ICollection<FF_Product_SubTable> FF_Product_SubTable { get; set; }
        public virtual FF_Product_Variants FF_Product_Variants { get; set; }
        public virtual FF_Products FF_Products { get; set; }
    }
}
