//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FennyFeeds.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataContext : DbContext
    {
        public DataContext()
            : base("name=DataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FF_Account_Activity> FF_Account_Activity { get; set; }
        public DbSet<FF_Admin_Registration> FF_Admin_Registration { get; set; }
        public DbSet<FF_Cart_List> FF_Cart_List { get; set; }
        public DbSet<FF_Category> FF_Category { get; set; }
        public DbSet<FF_Contact> FF_Contact { get; set; }
        public DbSet<FF_Donate_Blood> FF_Donate_Blood { get; set; }
        public DbSet<FF_HomePage_Display_Product> FF_HomePage_Display_Product { get; set; }
        public DbSet<FF_Invoice_Table> FF_Invoice_Table { get; set; }
        public DbSet<FF_Pet_Details> FF_Pet_Details { get; set; }
        public DbSet<FF_Product_SubTable> FF_Product_SubTable { get; set; }
        public DbSet<FF_Product_Variants> FF_Product_Variants { get; set; }
        public DbSet<FF_Products> FF_Products { get; set; }
        public DbSet<FF_Purchase_Order_List> FF_Purchase_Order_List { get; set; }
        public DbSet<FF_Registration> FF_Registration { get; set; }
        public DbSet<FF_Request_Blood> FF_Request_Blood { get; set; }
        public DbSet<FF_Service_Area> FF_Service_Area { get; set; }
        public DbSet<FF_Shipping_Address> FF_Shipping_Address { get; set; }
        public DbSet<FF_Sub_Category> FF_Sub_Category { get; set; }
        public DbSet<FF_Subscription> FF_Subscription { get; set; }
        public DbSet<FF_User_Role> FF_User_Role { get; set; }
        public DbSet<FF_Variants_Value> FF_Variants_Value { get; set; }
        public DbSet<FF_Wish_List> FF_Wish_List { get; set; }
    }
}
